spring:
  application:
    name: footballapp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/footballapp}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    time-zone: UTC


api:
  football:
    base-url: ${API_FOOTBALL_BASE_URL:https://v3.football.api-sports.io}
    key: ${API_FOOTBALL_KEY}
    league-id: ${API_FOOTBALL_LEAGUE_ID}
    season: ${API_FOOTBALL_SEASON}
